### ISSUE TITLE
Create Kubernetes Manifest based on Docker-compose

### ISSUE THREAD

**Issue by nurlanf** [nurlanf/ada-linux-in-devops#4]
### Quick Overview

**Kubernetes:** An open-source platform designed to automate deploying, scaling, and managing containerized applications. It groups containers that make up an application into logical units for easy management and discovery.

**Difference with Docker:** While Docker provides a platform for building and running individual containers, Kubernetes goes a step further by providing a framework to run distributed systems resiliently, handling tasks like scaling, failover, and load balancing.

**Why Deploy to Kubernetes:** Kubernetes provides features like self-healing (automatic restarts, rescheduling, and replicating containers), scaling (based on CPU usage or custom metrics), and load balancing, making it ideal for production-grade, large-scale deployments.

Diagrams here: https://phoenixnap.com/kb/understanding-kubernetes-architecture-diagrams

### Tasks

- [ ] Create deployment manifest and test it in `ada-test` namespace
- [ ] Create service manifest
- [ ] Increase replica and test rolling update of deployment (HA)
- [ ] Destroy `ada-test` namespace
