### ISSUE TITLE
Deploy to dev and prod via Helm

### ISSUE THREAD

**Issue by nurlanf** [nurlanf/ada-linux-in-devops#5]
### Quick Overview
**Helm:** Helm is a package manager for Kubernetes that allows developers and operators to more easily package, configure, and deploy applications and services onto Kubernetes clusters.

**Relation with Docker and Kubernetes:** Helm is used in conjunction with Docker and Kubernetes. Docker packages the application in a container, Kubernetes manages and orchestrates these containers, and Helm simplifies deployment and management of these applications on Kubernetes.

**Why use Helm:** Helm simplifies deployment of applications to Kubernetes by providing reusable 'Helm charts' (pre-configured Kubernetes resources), it manages complexity by providing the ability to define, install, and upgrade even the most complex Kubernetes application, and provides a simple way to share applications as charts.

Documentation for Helm 3: https://helm.sh/docs/

### Tasks

- [ ] Create Helm Package for new application
- [ ] Configure Health check
- [ ] Configure resources and MY_ENV variable according environment
