### ISSUE TITLE
Github workflow to build and push docker image

### ISSUE THREAD

**Issue by nurlanf** [nurlanf/ada-linux-in-devops#6]
### Quick overview

GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub. Make code reviews, branch management, and issue triaging work the way you want.

### Tasks

- [ ] During Pull Request, `docker build` should be passed
- [ ] During Pull Request, `helm lint` should be passed
- [ ] After merge to `main` branch, `docker push` should run to push image to docker registry
